language: node_js
node_js:
  - "8"

sudo: false

branches:
  only:
  - master

install:
  - yarn

script:
  - yarn build

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

deploy:
  - provider: pages
    skip-cleanup: true
    target-branch: gh-pages
    local-dir: dist
    github-token: $GITHUB_TOKEN
    on:
      branch: master